### ISSUE TITLE
Windows 10 to 11 phase out error after root switch to owner

### ISSUE THREAD

**Issue by quota360** [ankurk91/google-chat-electron#53]
```
Error: Failed to open
```

---

googleChatElectron 2.3.0
Electron 12.0.9
win32 10.0.19044
Locale: en-US

**Comment by ankurk91** [comment]
HI, please explain your error in detail, what was you trying to do ?

**Comment by ankurk91** [comment]
Looks like you have installed the app from Microsoft store

https://www.microsoft.com/en-ng/p/desktop-client-for-google-chat/9mzxbpl66066#activetab=pivot:overviewtab

I don't that app, I am not responsible for any issue occurred due to that app.

You can uninstall that app and install the original app from Github.
